CC = gcc
BIN = bin


q1:
	$(CC) -o $(BIN)/q1 q1.c

q2:
	$(CC) -o $(BIN)/q2 q2.c

q3:
	$(CC) -o $(BIN)/q3 q3.c

q5:
	$(CC) -o $(BIN)/q5 q5.c

q8:
	$(CC) -o $(BIN)/q8 q8.c

.PHONY: all

all: q1 q2 q3 q5 q8